<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="481370" started-at="2017-05-16T12:33:34Z" finished-at="2017-05-16T12:41:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="481370" started-at="2017-05-16T12:33:34Z" finished-at="2017-05-16T12:41:35Z">
      <class name="bi3.tests.fnb.EndToEndFlow">
        <test-method status="PASS" signature="BeforeTest()[pri:0, instance:bi3.tests.fnb.EndToEndFlow@42d80b78]" name="BeforeTest" is-config="true" duration-ms="4530" started-at="2017-05-16T18:03:34Z" finished-at="2017-05-16T18:03:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method status="PASS" signature="Initialize()[pri:0, instance:bi3.tests.fnb.EndToEndFlow@42d80b78]" name="Initialize" is-config="true" duration-ms="141" started-at="2017-05-16T18:03:38Z" finished-at="2017-05-16T18:03:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialize -->
        <test-method status="FAIL" signature="FullFlow()[pri:0, instance:bi3.tests.fnb.EndToEndFlow@42d80b78]" name="FullFlow" duration-ms="476668" started-at="2017-05-16T18:03:38Z" finished-at="2017-05-16T18:11:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at bi3.tests.fnb.EndToEndMadeToOrderTest.MOPVerification(EndToEndMadeToOrderTest.java:628)
	at bi3.tests.fnb.EndToEndFlow.FullFlow(EndToEndFlow.java:452)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FullFlow -->
        <test-method status="PASS" signature="AfterTest()[pri:0, instance:bi3.tests.fnb.EndToEndFlow@42d80b78]" name="AfterTest" is-config="true" duration-ms="0" started-at="2017-05-16T18:11:35Z" finished-at="2017-05-16T18:11:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- bi3.tests.fnb.EndToEndFlow -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
